const fs = require('fs');
const path = require('path');
const uuid = require('uuid/v4');

// We check if session.key file exists in the project root to load the session secret from.
// If not, we generate a new uuid and write it to that location.
let sessionSecret = '';
const sessionSecretPath = path.resolve(__dirname, '../session.key');
if (fs.existsSync(sessionSecretPath)) {
	sessionSecret = fs.readFileSync(sessionSecretPath);
} else {
	sessionSecret = uuid();

	fs.writeFileSync(sessionSecretPath, sessionSecret);
}

// The JWT secret will not be generated by this script. It is shared with all
// subsystems and thus resides in the project root, placed there on setup.
const jwtSecretPath = path.resolve(__dirname, '../jwt.key');
if (!fs.existsSync(jwtSecretPath)) {
	throw new Error('No jwt.key file detected in root. This key is required.');
}

module.exports = {
	loginViewPath: path.resolve(__dirname, 'views/login.html'),
	usersDbPath: path.resolve(__dirname, '../users.json'),
	sessionSecret: sessionSecret,
	jwt: {
		secret: fs.readFileSync(jwtSecretPath),
		issuer: 'sso.home.mateffy.me',
		audience: 'home.mateffy.me',
		expiresIn: 86400
	}
};
